<html>
<font size = 6 color = Red align = center>
Natural Language Processing - Banking Customer Reviews using Python<br/>
</font>
</html>

# Inspiration and orginal Notebook from Sulekha Alooravi

In [16]:
# import pandas as pd

In [19]:
# data

Unnamed: 0  Ratings                                            Reviews  \
0             0      5.0  I have been using BANK BAZAAR services for a w...   
1             1      3.0  I have taken personal loan from CASHE , my exp...   
2             2      4.0  For the first time i have taken financial prod...   
3             3      4.0  My personal loan was taken with HDFC BANK , th...   
4             4      4.0  I have taken a personal loan from the HDFC ban...   
5             5      4.5  BankBazaar is a smooth platform to compare and...   
6             6      2.0  I've taken a personal loan from the Kotak Mahi...   
7             7      5.0  I've been  using the BankBazaar platform for a...   
8             8      5.0  I have taken a personal loan from the ICICI ba...   
9             9      3.0  I've been using the BankBazaar platform for a ...   
10           10      4.0  I've taken a short term loan from the CashE on...   
11           11      5.0  I've been using the BankBazaar platform for a ...   
12           12      5.0  I've taken a personal loan from the IndusInd b...   
13           13      4.0  I've taken an insta loan from the HDFC for 1 l...   
14           14      5.0  I'm really happy about the services of BankBaz...   
15           15      4.0  I've taken a personal loan from the INDUDSIND ...   
16           16      4.0  My personal loan application was approved with...   
17           17      4.0  I am using the services of bankbazaar from las...   
18           18      5.0  My experience was very good with HDB personal ...   
19           19      3.0  My personal loan was taken with HDFC bank 10  ...   
20           20      5.0  My experience was good so far with bankbazaar,...   
21           21      3.0  I have taken a personal loan with Axis Bank an...   
22           22      4.0  The application process was too long for ICICI...   
23           23      5.0  BANK BAZAAR is a one stop solution for all the...   
24           24      4.5  I know bankbazaar.com from last 4-5 years, the...   
25           25      5.0  My personal loan was taken with IDFC bank. The...   
26           26      3.0  I have my personal loan application approved w...   
27           27      5.0  I know bankbazaar.com from last 2 months, it w...   
28           28      4.5  My experience was good with ICICI bank for per...   
29           29      5.0  I came to know about bankbazaar through google...   
..          ...      ...                                                ...   
962         966      5.0  My loan experience was excellent with ICICI ba...   
963         967      5.0  The services of this on line tool were pretty ...   
964         968      5.0  I have taken a personal loan from Icici bank, ...   
965         969      5.0  I have personal loan in this bank its been tak...   
966         970      5.0  I am having a good experience with this on lin...   
967         971      4.0  I have taken a personal loan from Cashe, the o...   
968         972      4.0  I have taken the services of this on line tool...   
969         973      4.5  I have taken a personal loan from Hdfc bank, t...   
970         974      5.0  My personal loan experience was good with AXIS...   
971         975      4.0  I have taken a personal loan from HDFC bank an...   
972         976      4.0  My personal loan experience was good with HDFC...   
973         977      3.5  This was my first time experience with bankbaz...   
974         978      3.5  My personal loan application was approved with...   
975         979      5.0  I am using the services of bankbazaar from las...   
976         980      4.0  My personal loan application was approved with...   
977         981      4.5  There was a quick response from the customer s...   
978         982      4.0  I have my application for personal loan approv...   
979         983      4.0  My experience with bankbazaar was good so far,...   
980         984      3.0  My experience was good with T

### Convert the data into dataframe

In [15]:
import pandas as pd

In [16]:
Reviews = pd.DataFrame({'Reviews': revws, 'Ratings': rates})

In [17]:
Reviews = Reviews.replace({r'\s+$': '', r'^\s+': ''}, regex = True).replace(r'\n', ' ', regex = True)

In [18]:
Reviews.drop_duplicates(inplace = True)

In [19]:
Reviews.count()

Ratings    992
Reviews    992
dtype: int64

In [20]:
Reviews.head(5)

Ratings                                            Reviews
0     5.0  I have been using BANK BAZAAR services for a w...
1     3.0  I have taken personal loan from CASHE , my exp...
2     4.0  For the first time i have taken financial prod...
3     4.0  My personal loan was taken with HDFC BANK , th...
4     4.0  I have taken a personal loan from the HDFC ban...

In [21]:
Reviews.dtypes

Ratings    object
Reviews    object
dtype: object

In [22]:
Reviews['Ratings'] = Reviews['Ratings'].astype(float)

In [23]:
Reviews.dtypes

Ratings    float64
Reviews     object
dtype: object

### Calculate sentiment

In [24]:
def calculate_sentiment(reviews):
    if reviews['Ratings'] < 4.0:
        return 0   #Negative
    else:
        return 1   #Positive

In [25]:
Reviews["Sentiment"] = Reviews.apply(calculate_sentiment, axis=1)

In [26]:
Reviews.to_csv("BankReviews.csv")

### Save data in the form of csv

### Let us store Reviews and Sentiments as arrays since it would be more suitable to do further processing and feature extraction

In [25]:
text, y = data.Reviews, data.Sentiment

In [47]:
text

0      I have been using BANK BAZAAR services for a w...
1      I have taken personal loan from CASHE , my exp...
2      For the first time i have taken financial prod...
3      My personal loan was taken with HDFC BANK , th...
4      I have taken a personal loan from the HDFC ban...
5      BankBazaar is a smooth platform to compare and...
6      I've taken a personal loan from the Kotak Mahi...
7      I've been  using the BankBazaar platform for a...
8      I have taken a personal loan from the ICICI ba...
9      I've been using the BankBazaar platform for a ...
10     I've taken a short term loan from the CashE on...
11     I've been using the BankBazaar platform for a ...
12     I've taken a personal loan from the IndusInd b...
13     I've taken an insta loan from the HDFC for 1 l...
14     I'm really happy about the services of BankBaz...
15     I've taken a personal loan from the INDUDSIND ...
16     My personal loan application was approved with...
17     I am using the services 

In [48]:
type(text)

pandas.core.series.Series

### Split the data into train and test at a ratio of 70:30

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
text_train, text_test, y_train, y_test = train_test_split(text, y, test_size=0.33, random_state=42)

In [49]:
text_train

333    Through the bankbazaar only i got to know abou...
528    AXIS BANK FIT FOR NOTHING - WORST BANK IN INDI...
464    I have taken my personal loan with TATA CAPITA...
361    My credit card was taken with ICICI Bank.I am ...
172    My personal loan is with HDFC bank and the pro...
125    Every thing is good with Bankbazaar.com, they ...
650    I had chosen to go with them since the interes...
408    My personal loan was taken with TATA CAPITAL. ...
895    It had been a very good experience with them a...
90     My personal loan was taken with TATA CAPITAL. ...
931    I've been using the BankBazaar platform for a ...
181    I have taken a personal loan with Kotak Mahind...
274    It was a good experience with bankbazaar so fa...
887    Initially the process started well but later o...
69     My personal loan is with ICICI Bank and the pr...
291    I have taken a personal loan from Kotak Mahind...
131    I have taken my personal loan with CASHE.The l...
300    I've taken a personal lo

In [50]:
text_test

213    I have my personal loan application approved w...
331    Information available on the website is accura...
501    My personal loan was taken with FULLERTON .The...
309    Applications and the website are easy to  use ...
88     My personal loan was taken with HDFC Bank 4 ye...
535    My personal loan was taken with FULLERTON 1 mo...
280    My experience was good so far with bankbazaar,...
107    We can say it as average . product and documen...
59     It was a very fast process I have chosen this ...
506    I have taken a personal loan with Bajaj finser...
359    My personal loan was taken with KOTAK BANK 1 y...
445    I have taken my personal loan with HDFC BANK 1...
70     BANK BAZAAR is a good platform for all the fin...
96     I have taken a personal loan from HDFC Bank. I...
859    I have taken personal loan from Hdfc bank . Am...
750    I have taken my personal loan with HDFC bank. ...
865    It is okay to loan get rejected. There should ...
934    BankBazaar is a smooth p

### Explore train and test data

In [28]:
import numpy as np

In [29]:
np.unique(y_train)

array([0, 1])

In [30]:
np.unique(y_test)

array([0, 1])

In [31]:
print("Samples per Sentiment (training): {}".format(np.bincount(y_train)))

Samples per Sentiment (training): [136 528]


In [32]:
print("Samples per Sentiment (testing): {}".format(np.bincount(y_test)))

Samples per Sentiment (testing): [ 68 260]


### Feature Extraction

<html>
<font size = 4>
<b> Rescaling the Data with tf-idf </b> <br /></font>
<font>
One of the approaches to extract features from test is to
rescale features by how informative we expect them to be. One of the most common
ways to do this is using the term frequency–inverse document frequency (tf-idf)
method. Let us create a function for the same.
</font>
</html> 
\begin{equation*}
\text{tfidf}(w, d) = \text{tf} \log\big(\frac{N + 1}{N_w + 1}\big) + 1
\end{equation*}

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [34]:
def tfidf_extractor(corpus, ngram_range=(1,1)):    
    vectorizer = TfidfVectorizer(min_df=1, 
                                 norm='l2',
                                 smooth_idf=True,
                                 use_idf=True,
                                 ngram_range=ngram_range)
    features = vectorizer.fit_transform(corpus)
    return vectorizer, features

In [35]:
tfidf_vectorizer, tfidf_train_features = tfidf_extractor(text_train)  
tfidf_test_features = tfidf_vectorizer.transform(text_test) 

In [51]:
tfidf_test_features.data

array([0.15152635, 0.16255872, 0.15788504, ..., 0.14871696, 0.12909404,
       0.15549465])

In [52]:
tfidf_test_features

<328x1148 sparse matrix of type '<class 'numpy.float64'>'
	with 10675 stored elements in Compressed Sparse Row format>

In [36]:
from sklearn import metrics

In [37]:
def get_metrics(true_labels, predicted_labels):
    print ('Accuracy:', np.round(metrics.accuracy_score(true_labels,predicted_labels),2))
    print ('Precision:', np.round(metrics.precision_score(true_labels,predicted_labels,average='weighted'),2))
    print ('Recall:', np.round(metrics.recall_score(true_labels, predicted_labels,average='weighted'),2))
    print ('F1 Score:', np.round(metrics.f1_score(true_labels, predicted_labels,average='weighted'),2)) 

In [38]:
def train_predict_evaluate_model(classifier,train_features, train_labels, test_features, test_labels):
    # build model    
    classifier.fit(train_features, train_labels)
    # predict using model
    predictions = classifier.predict(test_features) 
    # evaluate model prediction performance   
    get_metrics(true_labels=test_labels, 
                predicted_labels=predictions)
    return predictions 

### Multinomial Naive Bayes with tfidf features   

In [39]:
from sklearn.naive_bayes import MultinomialNB

In [40]:
mnb_best = MultinomialNB(alpha = 0.001,fit_prior = True)

In [53]:
mnb_best  

MultinomialNB(alpha=0.001, class_prior=None, fit_prior=True)

In [41]:
mnb_tfidf_predictions = train_predict_evaluate_model(classifier=mnb_best,
                                           train_features=tfidf_train_features,
                                           train_labels=y_train,
                                           test_features=tfidf_test_features,
                                           test_labels=y_test)

Accuracy: 0.78
Precision: 0.73
Recall: 0.78
F1 Score: 0.74


### Confusion Matrix

In [42]:
cm = metrics.confusion_matrix(y_test, mnb_tfidf_predictions)
pd.DataFrame(cm, index=range(0,2), columns=range(0,2))

0    1
0  12   56
1  16  244

### Incorrect Predictions

In [44]:
import re

In [45]:
print ("*******[0 - Negative, 1 - Positive]*******")
for document, label, predicted_label in zip(text_test, y_test, mnb_tfidf_predictions):
    for i in range(0,2):
        if label == i and predicted_label != i:
            print ("Actual Label:", +label)
            print ("Predicted Label:", +predicted_label)
            print ("Review:", re.sub('\n', ' ', document))

*******[0 - Negative, 1 - Positive]*******
Actual Label: 0
Predicted Label: 1
Review: My personal loan was taken with FULLERTON .The process was very good but their processing fee was very high.The loan amount was 1,54,000 and the interest rate was satisfactory .The tenure period was 5 years. I had a smooth and hassle  free
Actual Label: 0
Predicted Label: 1
Review: My personal loan was taken with HDFC Bank 4 years back. The loan amount was 1.9 lakhs  and the interest rate was very high . The tenure   period was 4 years . I had a good experience  and i had a very smooth process also. Their processing fee was also too high.My overall experience was good.
Actual Label: 0
Predicted Label: 1
Review: My personal loan was taken with FULLERTON 1 month back.The loan amount was 10 lakhs  and the interest rate was very high. Te tenure period was 5 years. The process was quite good and excellent . I haven't faced any issues and the documentation  was smooth but  The processing  fee was high.
Actu