In [4]:
!pip install gym

    100% |████████████████████████████████| 1.6MB 1.1MB/s eta 0:00:01
    100% |████████████████████████████████| 1.0MB 1.2MB/s ta 0:00:011
  Running setup.py bdist_wheel for gym ... done
  Stored in directory: /home/thompson/.cache/pip/wheels/e9/26/9b/8a1a6599a91077a938ac4348cc3d3ac84bfab0dbfddeb4c6e7
Successfully built gym


In [5]:
# Import all libraries

import numpy as np
import gym
import random
import time
from IPython.display import clear_output 

In [6]:
# Create our Environment
env = gym.make('FrozenLake-v0')

In [8]:
# Construct Q-table and initialise all values to zero
action_space_size = env.action_space.n       #Columns
state_space_size = env.observation_space.n   #Rows

q_table = np.zeros((state_space_size, action_space_size)) # Initialize all values in Q-table to zero

print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [42]:
# Create and initialize all parameters needed to implement the Q-learning Algorithm

num_episodes = 10000  # total number of episodes the agent can play in the entire environment during training
max_steps_per_episode = 100  # number of maximum steps that can be taken in each episode

learning_rate = 0.01  # usually denoted by alpha
discount_rate = 0.99  # usually  denoted by gamma


# Exploration and Exploitation tradeoffs::::: Epsilon Greedy Strategy (EGS)
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


In [43]:
# List to hold all rewards
rewards_all_episodes = []

# Q-Learning Algorithm
for episode in range(num_episodes):
    state = env.reset()  # Reset the state of the environment back to the starting state. ie. optimizer.zero_grad()
    
    done = False  #keeps track of whether or not the episode is finshed
    rewards_current_episode = 0  #keep track of rewards in each episode
    
    for step in range(max_steps_per_episode):
        #Exploration - Exploitation Tradeoffs
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])  #chose the action that has the highest Q-value
        else:
            action = env.action_space.sample()   #sample an action randomly
            
        new_state, reward, done, info = env.step(action)
    
     # Update Q-table for Q(s, a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

        state = new_state
        rewards_current_episode += reward

        if done == True:
            break
        

    # Exploration Rate Decay
    exploration_rate = min_exploration_rate + \
     (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    rewards_all_episodes.append(rewards_current_episode)

# Calculate and Print the average rewards per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes / 1000)
count = 1000
print('******Average Reward Per Thousand Episodes******\n')
for r in rewards_per_thousand_episodes:
    print(count, ': ', str(sum(r/1000)))
    count += 1000



******Average Reward Per Thousand Episodes******

1000 :  0.05600000000000004
2000 :  0.21800000000000017
3000 :  0.4290000000000003
4000 :  0.5400000000000004
5000 :  0.6500000000000005
6000 :  0.6750000000000005
7000 :  0.6730000000000005
8000 :  0.6840000000000005
9000 :  0.7000000000000005
10000 :  0.7170000000000005


In [44]:
# print Updated Q-table
print('\n\n******Q-Table******\n')
print(q_table)



******Q-Table******

[[0.55446532 0.52777966 0.52513884 0.52060363]
 [0.30933553 0.33965994 0.33777074 0.49445093]
 [0.42760356 0.42317638 0.41762538 0.46644861]
 [0.34070337 0.29662277 0.30863137 0.45367859]
 [0.57115639 0.36578384 0.39490676 0.34260269]
 [0.         0.         0.         0.        ]
 [0.34859241 0.20417127 0.26009159 0.0997695 ]
 [0.         0.         0.         0.        ]
 [0.40315167 0.41073105 0.39033343 0.60369369]
 [0.48367427 0.65069709 0.48560206 0.423277  ]
 [0.62521692 0.41841201 0.44053622 0.36704017]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.45359024 0.52142208 0.74357422 0.46693432]
 [0.73250472 0.87193851 0.79380737 0.77943657]
 [0.         0.         0.         0.        ]]


In [45]:
 #Q-Learning Frozen Lake
for episode in range(3):
    state = env.reset()
    done = False
    print('*****Episode ', episode+1, '*****\n\n\n\n')
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait = True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait = True)
            env.render()
            
            if reward == 1:
                print('*****You Reached the Goal****')
                time.sleep(3)
            else:
                print('****You fell through the Hole****')
                time.sleep(3)
            clear_output(wait = True)
            break
        state = new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
*****You Reached the Goal****


In [47]:
# Cart Pole Project

env = gym.make('CartPole-v0')
env.reset()

for _ in range(1000):
    env.render()
    env.step(env.action_space.sample())
    
env.close()

/home/thompson/.local/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
